name: Slides Webinar Alfaomega

on:
  push:
    branches: [main]
    paths:
      - src/doc/**
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 14 * * 5"
  # workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-20.04

    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout init --cone
          git sparse-checkout set src/doc
          git checkout

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/texlive:latest
          options: -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo -u aur yay -Syu texlive-latexextra texlive-pictures texlive-science texlive-fontsextra texlive-bibtexextra biber inkscape doxygen python-sphinx ttf-fira-code cmake --needed --noconfirm
            sudo -u aur echo 'export PATH="/usr/bin/vendor_perl:$PATH"' >> /home/aur/.bashrc
            sudo -u aur source /home/aur/.bashrc
            cd /work
            ls -l
            ./run.sh

      - name: Check pdf files
        run: |
          find build/doc/ -type f -name "*.pdf" -exec file -- {} + | grep -q ' PDF '

      - name: "Tar files"
        run: |
          tar --zstd -cf PDF.tar.zst build/doc/*.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: PDF-artifact
          path: PDF.tar.zst
          if-no-files-found: error
          retention-days: 90
